# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBCfvxGjG0w-l8tfsIC-RLw74QC6dHR6
"""

import os
import streamlit as st
import google.generativeai as genai

# ---------- CONFIGURATION ----------
st.set_page_config(page_title="AI Career Path Recommender", page_icon="🎯")

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# ---------- APP TITLE ----------
st.title("🎓 AI Career Path Recommender using Google Gemini 2.5 Flash")
st.markdown("Get personalized career guidance powered by **Gemini 2.5 Flash** ⚡")

# ---------- INPUT FIELDS ----------
degree = st.text_input("🎓 Enter your degree:")
skills = st.text_area("🧠 List your current skills (comma separated):")
interests = st.text_area("💡 Mention your interests or favorite domains:")
goals = st.text_area("🚀 Describe your career goals (short or long term):")

# ---------- GENERATE RECOMMENDATIONS ----------
if st.button("Generate Career Recommendations"):
    with st.spinner("Generating personalized career roadmap using Gemini 2.5 Flash..."):
        prompt = f"""
        You are a professional career advisor. Based on the following profile,
        suggest 3 suitable career paths, 5 skills to learn for each, and 3 online courses.
        Explain briefly why these options are suitable.

        Degree: {degree}
        Skills: {skills}
        Interests: {interests}
        Career Goals: {goals}
        """

        try:
            model = genai.GenerativeModel("models/gemini-2.5-flash")
            response = model.generate_content(prompt)

            output = response.text or "No response generated."
            st.success("✅ Career Recommendations Generated Successfully!")
            st.markdown("---")
            st.markdown(output)

        except Exception as e:
            st.error(f"Error: {e}")